# Generated by Django 4.1 on 2022-10-12 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cp', models.CharField(max_length=50)),
                ('tipoCampo_cp', models.CharField(max_length=50)),
                ('value_cp', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=100)),
                ('empresa_cliente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=15)),
                ('orden_fase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaseTUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_faseTUS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_permiso', models.CharField(max_length=100)),
                ('nombre_permiso', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['descripcion_permiso'],
            },
        ),
        migrations.CreateModel(
            name='PrioridadTUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('color', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'PrioridadTUs',
                'verbose_name_plural': 'PrioridadTUs',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('fecha_ini_proyecto', models.DateField(null=True)),
                ('fecha_fin_proyecto', models.DateField(null=True)),
                ('descripcion_proyecto', models.CharField(default='', max_length=100)),
                ('sprint_dias', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('cliente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('estado_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estado')),
                ('miembro_proyecto', models.ManyToManyField(to='usuario.miembroequipo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre_proyecto'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion_rol', models.CharField(max_length=100)),
                ('permiso', models.ManyToManyField(to='usuario.permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['descripcion_rol'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sp', models.CharField(max_length=50)),
                ('fechaIni_sp', models.DateField(default=datetime.date.today)),
                ('fechaFIn_sp', models.DateField()),
                ('duracion_sp', models.IntegerField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('proyecto_sp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['nombre_sp'],
            },
        ),
        migrations.CreateModel(
            name='TipoUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_us', models.CharField(max_length=50)),
                ('descripcion_tipo_us', models.CharField(max_length=100)),
                ('flujo_tipo_us', models.JSONField(null=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('campoPer_tipo_us', models.ManyToManyField(to='usuario.campopersonalizado')),
                ('prioridad_tipo_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.prioridadtus')),
            ],
            options={
                'verbose_name': 'Tipo User Story',
                'verbose_name_plural': 'Tipos de User Story',
                'ordering': ['nombre_tipo_us'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('df_rol', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_usuario'],
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_us', models.CharField(max_length=50)),
                ('descripcion_us', models.CharField(max_length=50)),
                ('tiempoEstimado_us', models.IntegerField(null=True)),
                ('estadoActual_us', models.CharField(max_length=20, null=True)),
                ('duracion_us', models.IntegerField(default=0)),
                ('fechaIni_us', models.DateField(auto_now_add=True)),
                ('fechaMod_us', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('asignadoUsu_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.miembroequipo')),
                ('proyecto_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto')),
                ('tipo_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'ordering': ['nombre_us'],
            },
        ),
        migrations.CreateModel(
            name='TipoUs_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto')),
                ('tipoUs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tablero', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('faseTUS_tablero', models.ManyToManyField(to='usuario.fasetus')),
                ('sprint_tablero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint')),
                ('tipo_us_fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='userStory_sp',
            field=models.ManyToManyField(blank=True, to='usuario.userstory'),
        ),
        migrations.CreateModel(
            name='ProyectoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_proyecto_rol', models.CharField(default='', max_length=100)),
                ('proyecto', models.ManyToManyField(to='usuario.proyecto')),
                ('rol', models.ManyToManyField(to='usuario.rol')),
            ],
            options={
                'verbose_name': 'ProyectoRol',
                'verbose_name_plural': 'ProyectoRoles',
            },
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_rol',
            field=models.ManyToManyField(to='usuario.rol'),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_usuario',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='fasetus',
            name='tipo_us_faseTUS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory'),
        ),
        migrations.AddField(
            model_name='fase',
            name='tipoUs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory'),
        ),
    ]
