# Generated by Django 4.1 on 2022-09-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipo',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
