# Generated by Django 4.1 on 2022-11-16 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historiales',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='historial',
            field=models.ManyToManyField(to='usuario.historial'),
        ),
    ]
