# Generated by Django 4.1 on 2022-10-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintcolaborador',
            name='horasDisponibles',
            field=models.IntegerField(default=0),
        ),
    ]
