# Generated by Django 4.1 on 2022-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
