# Generated by Django 4.1 on 2022-10-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sprint_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad_sprint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad_tecnica',
            field=models.IntegerField(default=0),
        ),
    ]
