# Generated by Django 4.1 on 2022-11-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hora_trabajada',
            new_name='HoraTrabajada',
        ),
    ]
