# Generated by Django 4.1 on 2022-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.CharField(default='observador', max_length=100),
        ),
    ]
