# Generated by Django 4.1 on 2022-10-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='colaborador',
            new_name='colaborador_sp',
        ),
        migrations.RenameField(
            model_name='sprintcolaborador',
            old_name='usuario',
            new_name='colaborador',
        ),
    ]
