# Generated by Django 4.1 on 2022-10-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='colaborador',
            new_name='colaborador_sp',
        ),
        migrations.RenameField(
            model_name='sprintcolaborador',
            old_name='usuario',
            new_name='colaborador',
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase'),
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='miembro_usuario',
        ),
        migrations.CreateModel(
            name='SprintUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.userstory')),
            ],
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='userStory_sp',
            field=models.ManyToManyField(blank=True, to='usuario.sprintuserstory'),
        ),
    ]
