# Generated by Django 4.1 on 2022-10-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_colaborador_sprint_colaborador_sp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembroequipo',
            name='miembro_proyecto',
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='miembro_usuario',
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_usuario',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
    ]
