# Generated by Django 4.1 on 2022-10-10 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_campopersonalizado_fase_fasetus_prioridadtus_sprint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase',
            old_name='cod_fase',
            new_name='orden_fase',
        ),
        migrations.RemoveField(
            model_name='tipouserstory',
            name='proyecto_tipo_us',
        ),
        migrations.AddField(
            model_name='fase',
            name='tipoUs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory'),
        ),
        migrations.CreateModel(
            name='TipoUs_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto')),
                ('tipoUs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory')),
            ],
        ),
    ]
