# Generated by Django 4.1 on 2022-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_historial_proyecto_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
