# Generated by Django 4.1 on 2022-10-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_proyecto_estado_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='estado_proyecto',
            new_name='estado',
        ),
    ]
