# Generated by Django 4.1 on 2022-09-26 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_tipouserstory_userstory_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tablero', models.CharField(max_length=50)),
                ('descripcion_tablero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS_orden', models.IntegerField()),
                ('PS_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto')),
                ('PS_sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint')),
            ],
            options={
                'verbose_name': 'Sprint por Proyecto',
                'verbose_name_plural': 'Sprints por Proyecto',
                'ordering': ['PS_orden'],
            },
        ),
    ]
