# Generated by Django 4.1 on 2022-11-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_comentario_delete_comentarios_userstory_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='duracion_us',
            new_name='tiempoTrabajado',
        ),
    ]
