# Generated by Django 4.1 on 2022-10-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_comentarios_proyecto_sprint_actual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'ordering': ['orden_fase'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['-prioridad_final'], 'verbose_name': 'User Story', 'verbose_name_plural': 'User Stories'},
        ),
    ]
