# Generated by Django 4.1 on 2022-10-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_sprintcolaborador_horasdisponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre_permiso',
            field=models.CharField(max_length=100),
        ),
    ]
