# Generated by Django 4.1 on 2022-11-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_hora_trabajada_horatrabajada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horatrabajada',
            options={'ordering': ['fecha_creacion']},
        ),
    ]
