# Generated by Django 4.1 on 2022-10-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_colaborador_sprint_colaborador_sp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.userstory')),
            ],
        ),
        migrations.AlterField(
            model_name='sprint',
            name='userStory_sp',
            field=models.ManyToManyField(blank=True, to='usuario.sprintuserstory'),
        ),
    ]
