# Generated by Django 4.1 on 2022-11-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_userstory_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['estado'], 'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
    ]
