# Generated by Django 4.1 on 2022-11-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_historial_proyecto_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
