# Generated by Django 4.1 on 2022-09-07 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_miembroequipo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 13, 42, 18, 219673)),
        ),
    ]
