# Generated by Django 4.1 on 2022-11-25 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_horatrabajada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horatrabajada',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
