# Generated by Django 4.1 on 2022-08-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_permiso_alter_usuario_options_remove_usuario_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='permisos',
            new_name='permiso',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_roles',
            new_name='rol',
        ),
    ]
