# Generated by Django 4.1 on 2022-10-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_sprintuserstory_alter_sprint_userstory_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase'),
        ),
    ]
