# Generated by Django 4.1 on 2022-11-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_duracion_us_userstory_tiempotrabajado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'comenario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
