# Generated by Django 4.1 on 2022-09-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_proyecto_id_sprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id_sprints',
        ),
    ]
