# Generated by Django 4.1 on 2022-11-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_comentario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='horas',
            field=models.IntegerField(null=True),
        ),
    ]
