# Generated by Django 4.1 on 2022-09-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_permisos_rol_permiso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
