# Generated by Django 4.1 on 2022-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_proyecto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
