# Generated by Django 4.1 on 2022-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_proyecto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('proyecto', models.ManyToManyField(to='usuario.proyecto')),
                ('rol', models.ManyToManyField(to='usuario.rol')),
            ],
            options={
                'verbose_name': 'ProyectoRol',
                'verbose_name_plural': 'ProyectoRoles',
            },
        ),
    ]
