# Generated by Django 4.1 on 2022-09-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_proyecto_id_sprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='userStory_sp',
        ),
        migrations.AddField(
            model_name='sprint',
            name='userStory_sp',
            field=models.ManyToManyField(blank=True, to='usuario.userstory'),
        ),
    ]
