# Generated by Django 4.1 on 2022-09-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_proyectorol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectorol',
            name='descripcion',
        ),
    ]
