# Generated by Django 4.1 on 2022-09-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_sprint_userstory_sp_sprint_userstory_sp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto_Sprint',
            new_name='ProyectoSprint',
        ),
    ]
