# Generated by Django 4.1 on 2022-10-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_proyecto_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouserstory',
            name='prioridad_tipo_us',
        ),
        migrations.AddField(
            model_name='userstory',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
