# Generated by Django 4.1 on 2022-09-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_proyectorol_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['descripcion_permiso'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['descripcion_rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RenameField(
            model_name='permiso',
            old_name='descripcion',
            new_name='descripcion_permiso',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='descripcion',
            new_name='descripcion_rol',
        ),
    ]
