# Generated by Django 4.1 on 2022-09-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_cliente_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['nombre_proyecto'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Estado_proyecto',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_proyecto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_proyecto',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='df_rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_ini_proyecto',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro_descripcion', models.CharField(max_length=100)),
                ('miembro_rol', models.ManyToManyField(to='usuario.rol')),
                ('miembro_usuario', models.ManyToManyField(to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['miembro_descripcion'],
            },
        ),
    ]
