# Generated by Django 4.1 on 2022-10-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_tipouserstory_prioridad_tipo_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridad_negocio',
            field=models.IntegerField(default=0),
        ),
    ]
