# Generated by Django 4.1 on 2022-09-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_permiso_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectorol',
            name='descripcion_proyecto_rol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
