# Generated by Django 4.1 on 2022-09-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_rename_proyecto_sprint_proyectosprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectosprint',
            options={'ordering': ['orden_PS'], 'verbose_name': 'Sprint por Proyecto', 'verbose_name_plural': 'Sprints por Proyecto'},
        ),
        migrations.RenameField(
            model_name='proyectosprint',
            old_name='PS_orden',
            new_name='orden_PS',
        ),
        migrations.RenameField(
            model_name='proyectosprint',
            old_name='PS_proyecto',
            new_name='proyecto_PS',
        ),
        migrations.RenameField(
            model_name='proyectosprint',
            old_name='PS_sprint',
            new_name='sprint_PS',
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(choices=[('TODO', 'Por Hacer'), ('DOING', 'Haciendo'), ('DONE', 'Hecho'), ('CANC', 'Cancelado')], default='TODO', max_length=15)),
                ('descripcion_fase', models.CharField(max_length=100)),
                ('userStory_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.userstory')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['nombre_fase'],
            },
        ),
        migrations.AddField(
            model_name='tablero',
            name='fase_tablero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase'),
            preserve_default=False,
        ),
    ]
