# Generated by Django 4.1 on 2022-09-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_cliente_options_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Estado_proyecto',
            new_name='estado_proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='miembro_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.miembroequipo'),
            preserve_default=False,
        ),
    ]
