# Generated by Django 4.1 on 2022-09-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_proyectosprint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='fase_tablero',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase'),
        ),
    ]
