# Generated by Django 4.1 on 2022-09-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_campopersonalizado_sprint_proyecto_sp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadTUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'PrioridadTUs',
                'verbose_name_plural': 'PrioridadTUs',
                'ordering': ['valor'],
            },
        ),
    ]
