# Generated by Django 4.1 on 2022-09-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_prioridadtus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipouserstory',
            name='prioridad_tipo_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.prioridadtus'),
        ),
    ]
