# Generated by Django 4.1 on 2022-09-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_tipouserstory_prioridad_tipo_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='prioridadTec_us',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='valorNegocio_us',
        ),
        migrations.AlterField(
            model_name='userstory',
            name='duracion_us',
            field=models.IntegerField(default=0),
        ),
    ]
