# Generated by Django 4.1 on 2022-09-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_userstory_prioridadtec_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='miembro_proyecto',
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto'),
        ),
        migrations.RemoveField(
            model_name='miembroequipo',
            name='miembro_usuario',
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='miembro_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
