# Generated by Django 4.1 on 2022-09-30 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_fase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tablero',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
