# Generated by Django 4.1 on 2022-10-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_sprint_fecha_creacion_tipouserstory_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='fecha_creacion',
        ),
    ]
