# Generated by Django 4.1 on 2022-09-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_proyecto_miembro_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='sprint_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint'),
        ),
        migrations.AddField(
            model_name='tablero',
            name='sprint_tablero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nombre_fase',
            field=models.CharField(default='TODO', max_length=15),
        ),
    ]
