# Generated by Django 4.1 on 2022-10-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_remove_sprint_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='fechaIni_sp',
        ),
    ]
