# Generated by Django 4.1 on 2022-09-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_sprint_fecha_creacion_tablero_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadtus',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
