# Generated by Django 4.1 on 2022-10-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_remove_sprint_fechaini_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='fecha_creacion',
        ),
    ]
