# Generated by Django 4.1 on 2022-10-06 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_remove_userstory_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouserstory',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='sprint',
            name='fechaIni_sp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
