# Generated by Django 4.1 on 2022-10-06 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_remove_tipouserstory_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={},
        ),
        migrations.RenameField(
            model_name='fase',
            old_name='descripcion_fase',
            new_name='cod_fase',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='userStory_fase',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='descripcion_tablero',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='fase_tablero',
        ),
        migrations.AddField(
            model_name='prioridadtus',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tablero',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tablero',
            name='sprint_tablero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.sprint'),
        ),
        migrations.AddField(
            model_name='tablero',
            name='tipo_us_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory'),
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userstory',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nombre_fase',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='FaseTUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_faseTUS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.fase')),
                ('tipo_us_faseTUS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipouserstory')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.AddField(
            model_name='tablero',
            name='faseTUS_tablero',
            field=models.ManyToManyField(to='usuario.fasetus'),
        ),
    ]
