# Generated by Django 4.1 on 2022-10-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_prioridadtus_color'),
        ('usuario', '0019_alter_fase_options_and_more'),
    ]

    operations = [
    ]
