# Generated by Django 4.1 on 2022-10-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_tipous_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='proyecto_us',
        ),
    ]
