# Generated by Django 4.1 on 2022-10-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_remove_userstory_proyecto_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouserstory',
            name='proyecto_tipo_us',
        ),
        migrations.AddField(
            model_name='userstory',
            name='proyecto_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.proyecto'),
        ),
    ]
